version: '3'

networks:
  internal_network:
    internal: true
  public_network:

services:
  gpt-researcher:
    pull_policy: always
    image: gptresearcher/gpt-researcher
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      LOGGING_LEVEL: INFO
    volumes:
      - ${PWD}/my-docs:/usr/src/app/my-docs:rw
      - ${PWD}/outputs:/usr/src/app/outputs:rw
      - ${PWD}/logs:/usr/src/app/logs:rw
    user: root
    restart: always
    networks:
      - internal_network
    # Removed public port exposure
      
  gptr-nextjs:
    pull_policy: always
    image: gptresearcher/gptr-nextjs
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
      LOGGING_LEVEL: INFO
      NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID}
      # Updated API URL to use service name for internal communication
      NEXT_PUBLIC_GPTR_API_URL: http://gpt-researcher:8000
    build:
      dockerfile: Dockerfile.dev
      context: frontend/nextjs
    volumes:
      - /app/node_modules
      - ./frontend/nextjs:/app
      - ./frontend/nextjs/.next:/app/.next
      - ./outputs:/app/outputs
    restart: always
    ports:
      - 35479:3000
    networks:
      - internal_network
      - public_network


