# fly.toml app configuration file generated for agents on 2025-01-31T08:22:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agents'
primary_region = 'bos'

[[mounts]]
  source = 'output'
  destination = '/outputs'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
